version: "3.8"
services:
  filmorate:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/filmorate
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
#      - TZ=Europe/Moscow

  db:
    image: postgres:14.5-alpine3.16
    container_name: filmorate-postgres
    ports:
      - "6541:5432"
#        volumes:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=filmorate
#      - TZ=Europe/Moscow