DELETE FROM FRIENDSHIP;
DELETE FROM USER_LIKE;
DELETE FROM FILMORATE_USER;
DELETE FROM FILM;
DELETE FROM GENRE;
DELETE FROM MPA;

ALTER TABLE FRIENDSHIP ALTER COLUMN id RESTART WITH 1;
ALTER TABLE USER_LIKE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE FILMORATE_USER ALTER COLUMN id RESTART WITH 1;
ALTER TABLE FILM ALTER COLUMN id RESTART WITH 1;
ALTER TABLE GENRE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE MPA ALTER COLUMN id RESTART WITH 1;