CREATE TABLE IF NOT EXISTS filmorate_user (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100) UNIQUE,
    login varchar(100) UNIQUE,
    name varchar(100),
    birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active_user_id int,
    passive_user_id int,
    is_accepted boolean DEFAULT FALSE,
    FOREIGN KEY (active_user_id) REFERENCES filmorate_user(id),
    FOREIGN KEY (passive_user_id) REFERENCES filmorate_user(id)
);

CREATE TABLE IF NOT EXISTS genre (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS mpa (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(50)
);

CREATE TABLE IF NOT EXISTS film (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    description text,
    release_date date,
    duration_min int,
    genre_id int,
    mpa_id int,
    FOREIGN KEY (genre_id) REFERENCES genre(id),
    FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS user_like (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id int,
     film_id int,
     FOREIGN KEY (user_id) REFERENCES filmorate_user(id),
     FOREIGN KEY (film_id) REFERENCES film(id)
);