DELETE FROM friendship;
DELETE FROM likes;
DELETE FROM users;
DELETE FROM film_genres;
DELETE FROM films;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE films ALTER COLUMN id RESTART WITH 1;